spring:
  application:
    name: actuator-demo

management:
  server:
    port: 9091

  info:
    java:
      enabled: true

    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  metrics:
    tags:
      application: app-demo
      environment: ${ENVIRONMENT:local}

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0 # default is 0.1 (10%)

  zipkin:
    tracing:
      read-timeout: 1s
      connect-timeout: 10s
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    root: INFO
    org.springframework.web: OFF

  pattern:
    level: "%5p [${spring.application.name}][%X{traceId:-}:%X{spanId:-}]"
