management:
  server:
    port: 9091

  info:
    java:
      enabled: true

    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  metrics:
    tags:
      application: app-demo
      environment: ${ENVIRONMENT:local}

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  tracing:
    sampling:
      probability: 1.0 # default is 0.1 (10%)

logging:
  root:
    level: INFO

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
