management:
  info:
    java:
      enabled: true

    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  server:
    port: 9091

  metrics:
    tags:
      application: app-demo
      environment: ${ENVIRONMENT:local}
